name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:
    strategy:
      matrix:
        php: ['7.2', '7.3', '7.4']

    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
          composer install --prefer-dist --no-interaction

    - name: Run tests
      run: ./vendor/bin/phpunit --coverage-clover ./build/logs/clover.xml

    - name: Send code clover file to coveralls.io
      run: ./vendor/bin/php-coveralls -v
      env:
        COVERALLS_RUN_LOCALLY: 1
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
